# Generated by Django 5.2.5 on 2025-09-08 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('industry', models.CharField(blank=True, default='', max_length=200)),
                ('days', models.IntegerField(default=7)),
                ('limit', models.IntegerField(default=10)),
                ('result_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(unique=True)),
                ('title', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('text_html', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_ts', models.BigIntegerField(blank=True, null=True)),
                ('engagement', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_ts', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='api.source'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_ts'], name='api_post_publish_a30e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['source', '-published_ts'], name='api_post_source__eeed9d_idx'),
        ),
    ]
