# Generated by Django 5.1.12 on 2025-09-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fetchlog_post_source_delete_project_post_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchlog',
            name='search_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
