from __future__ import annotations

# Curated OEM / EV brand list (expand anytime)
AUTO_OEM_WHITELIST = {
    # Global majors
    "Toyota",
    "Volkswagen",
    "VW",
    "Audi",
    "Porsche",
    "Skoda",
    "Seat",
    "Cupra",
    "Mercedes-Benz",
    "Mercedes",
    "BMW",
    "Mini",
    "Rolls-Royce",
    "Stellantis",
    "Peugeot",
    "Citroën",
    "Opel",
    "Vauxhall",
    "Fiat",
    "Alfa Romeo",
    "Maserati",
    "Jeep",
    "Chrysler",
    "Dodge",
    "Ram",
    "Ford",
    "GM",
    "General Motors",
    "Chevrolet",
    "Cadillac",
    "Buick",
    "GMC",
    "Hyundai",
    "Kia",
    "Genesis",
    "Honda",
    "Acura",
    "Nissan",
    "Infiniti",
    "Mitsubishi",
    "Mazda",
    "Subaru",
    "Suzuki",
    "Volvo",
    "Polestar",
    "Saab",
    "Renault",
    "Dacia",
    "Tata",
    "Jaguar",
    "Land Rover",
    "JLR",
    "Mahindra",
    "Geely",
    "SAIC",
    "Great Wall",
    "GWM",
    "Changan",
    "BAIC",
    "FAW",
    "Dongfeng",
    # EV / new energy
    "Tesla",
    "BYD",
    "NIO",
    "XPeng",
    "Li Auto",
    "Rivian",
    "Lucid",
    "VinFast",
    "Fisker",
    "Faraday Future",
    "Canoo",
    "Nikola",
    # Chinese sub-brands
    "Aion",
    "Zeekr",
    "Lynk & Co",
    "Wuling",
    "Ora",
    "Haval",
    "HiPhi",
    "Avatr",
    "Seres",
    "Leapmotor",
    "Zotye",
    "Neta",
    # Others
    "Proton",
    "Perodua",
    "UAZ",
    "Lada",
    "GAC",
    "Zhejiang Geely",
}

# Accept phrases that look like brands even if not in whitelist
AUTO_SUFFIX_HINTS = {
    "Motors",
    "Motor",
    "Auto",
    "Automotive",
    "Mobility",
    "Cars",
    "Vehicles",
    "EV",
    "EVs",
    "Truck",
    "Trucks",
}

# Tickers we accept as shorthand for OEMs (optional)
TICKER_WHITELIST = {
    "TSLA",
    "GM",
    "F",
    "TM",
    "HMC",
    "VWAGY",
    "VWAPY",
    "MBGAF",
    "BMWYY",
    "STLA",
    "BYD",
    "RIVN",
    "LCID",
    "NIO",
    "XPEV",
}
