# # AI/collection_card/main_opportunities.py

# from pymongo import MongoClient
# import argparse
# import json
# import os
# import sys

# from .fetch_industry_articles import get_industry_articles
# from .generate_opportunities import generate_opportunities


# # at top
# import re
# from typing import Dict, Any

# def _build_industry_text_filter(industry_name: str) -> Dict[str, Any]:
#     """
#     Case-insensitive filter that matches ai_title, ai_summary, tags (array), and source.
#     - Escapes special regex chars in industry_name
#     - Allows flexible whitespace (e.g., "Electric   Vehicles")
#     """
#     if not industry_name:
#         return {}

#     # Escape regex specials, then allow variable whitespace between tokens
#     escaped = re.escape(industry_name.strip())
#     # turn "\ " into "\s+" so "Electric Vehicles" will match "Electric-vehicles", "Electric  Vehicles", etc.
#     flexible = re.sub(r"\\\s+", r"\\s+", escaped)

#     rx = {"$regex": flexible, "$options": "i"}

#     return {
#         "$or": [
#             {"ai_title": rx},
#             {"ai_summary": rx},
#             {"source": rx},
#             # tags is an array → must use $elemMatch with a regex
#             {"tags": {"$elemMatch": rx}},
#         ]
#     }


# # --- Mongo bootstrap (same style you're already using)
# MONGO_URI = os.getenv(
#     "MONGO_URI",
#     "mongodb+srv://ai_worker_user:YUiDJwjMqqBKEI70@cluster0.dqugl74.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
# )
# client = MongoClient(MONGO_URI)
# db = client["pace_database"]


# def get_company_context(company_name: str) -> dict:
#     """
#     Fetch company description + competitors for context.
#     Assumes collection: company_profiles
#     {
#       name: "Robotic Marketer",
#       description: "...",
#       competitors: ["Company A", "Company B", ...]
#     }
#     """
#     company = db.company_profiles.find_one({"name": company_name})
#     if not company:
#         raise ValueError(f"No company_profile found for '{company_name}'")

#     return {
#         "company": company["name"],
#         "description": company["description"],
#         "competitors": company.get("competitors", []),
#     }


# def log(msg: str, verbose: bool):
#     if verbose:
#         print(msg, file=sys.stderr)

# def run(
#     company_name: str,
#     industry_name: str,
#     limit: int = 20,
#     min_relevance: float = 0.4,
#     verbose: bool = False,
# ):
#     """
#     Programmatic entry point for generating growth/partnership/expansion opportunities.

#     Mirrors the CLI behavior in __main__.

#     Args:
#         company_name: Name of the company (must exist in company_profiles)
#         industry_name: Industry/topic/sector (e.g., "AI in retail")
#         limit: Max number of recent articles to consider (default 20)
#         min_relevance: Minimum relevance_score threshold (default 0.4)
#         verbose: Print debug messages if True

#     Returns:
#         List[dict]: structured opportunity insights generated by the AI layer
#     """
#     try:
#         log(f"🏢 Loading company context for {company_name}...", verbose)
#         company_ctx = get_company_context(company_name)

#         log(f"📰 Fetching {limit} recent '{industry_name}' articles...", verbose)
#         articles = get_industry_articles(
#             industry_name=industry_name,
#             limit=limit,
#             min_relevance=min_relevance,
#         )
#         log(f"✓ Found {len(articles)} industry-matching articles", verbose)

#         log("🤖 Generating opportunities...", verbose)
#         opps = generate_opportunities(
#             company_context=company_ctx,
#             industry_name=industry_name,
#             industry_articles=articles,
#         )
#         log(f"✓ Generated {len(opps)} opportunities", verbose)

#         return opps

#     except Exception as e:
#         raise RuntimeError(f"opportunities.run() failed: {e}") from e


# if __name__ == "__main__":
#     parser = argparse.ArgumentParser(
#         description="Generate growth/partnership/expansion opportunities for a given industry view."
#     )
#     parser.add_argument(
#         "company_name",
#         type=str,
#         help="Company name as stored in company_profiles"
#     )
#     parser.add_argument(
#         "industry_name",
#         type=str,
#         help="Industry/topic/sector currently being viewed (e.g. 'AI in retail', 'renewable energy')"
#     )
#     parser.add_argument(
#         "--limit",
#         type=int,
#         default=20,
#         help="How many recent industry articles to consider"
#     )
#     parser.add_argument(
#         "--min-relevance",
#         type=float,
#         default=0.4,
#         help="Minimum relevance_score threshold in ai_results"
#     )
#     parser.add_argument(
#         "--verbose",
#         action="store_true",
#         help="Show debug/info logs on stderr"
#     )

#     args = parser.parse_args()

#     try:
#         log(f"🏢 Loading company context for {args.company_name}...", args.verbose)
#         company_ctx = get_company_context(args.company_name)

#         log(f"📰 Fetching {args.limit} recent '{args.industry_name}' articles...", args.verbose)
#         articles = get_industry_articles(
#             industry_name=args.industry_name,
#             limit=args.limit,
#             min_relevance=args.min_relevance,
#         )
#         log(f"✓ Found {len(articles)} industry-matching articles", args.verbose)

#         log("🤖 Generating opportunities...", args.verbose)
#         opps = generate_opportunities(
#             company_context=company_ctx,
#             industry_name=args.industry_name,
#             industry_articles=articles,
#         )
#         log(f"✓ Generated {len(opps)} opportunities", args.verbose)

#         # Send clean JSON to stdout (frontend/BE reads this)
#         print(json.dumps(opps, indent=2))

#     except Exception as e:
#         print(f"ERROR: {e}", file=sys.stderr)
#         sys.exit(1)


# AI/collection_card/main_opportunities.py

from __future__ import annotations

from pymongo import MongoClient
import argparse
import json
import os
import sys
import re
from typing import Dict, Any, List

from .fetch_industry_articles import get_industry_articles
from .generate_opportunities import generate_opportunities

# --- Mongo bootstrap (same style you're already using)
MONGO_URI = os.getenv(
    "MONGO_URI",
    "mongodb+srv://ai_worker_user:YUiDJwjMqqBKEI70@cluster0.dqugl74.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0",
)
client = MongoClient(MONGO_URI)
db = client["pace_database"]


# ---------------------------
# Helpers
# ---------------------------


def log(msg: str, verbose: bool):
    if verbose:
        print(msg, file=sys.stderr)


def _build_industry_text_filter(industry_name: str) -> Dict[str, Any]:
    """
    Case-insensitive filter that matches ai_title, ai_summary, tags (array), and source.
    Escapes special regex chars and allows flexible whitespace.
    """
    if not industry_name:
        return {}

    escaped = re.escape(industry_name.strip())
    flexible = re.sub(r"\\\s+", r"\\s+", escaped)
    rx = {"$regex": flexible, "$options": "i"}

    return {
        "$or": [
            {"ai_title": rx},
            {"ai_summary": rx},
            {"source": rx},
            {"tags": {"$elemMatch": rx}},
        ]
    }


def get_company_context(company_name: str) -> dict:
    """
    Fetch company description + competitors for context (company_profiles schema).
    {
      name: "Robotic Marketer",
      description: "...",
      competitors: ["Company A", "Company B", ...]
    }
    """
    company = db.company_profiles.find_one({"name": company_name})
    if not company:
        raise ValueError(f"No company_profile found for '{company_name}'")

    return {
        "company": company["name"],
        "description": company.get("description", ""),
        "competitors": company.get("competitors", []),
    }


def _fetch_recent_generic_articles(
    limit: int = 20, min_relevance: float = 0.25
) -> List[Dict[str, Any]]:
    """
    Fallback: if industry-matching articles are too few, pull recent relevant ones globally.
    """
    cur = (
        db.ai_results.find(
            {"status": "done", "relevance_score": {"$gte": float(min_relevance)}},
            {
                "_id": 0,
                "ai_title": 1,
                "ai_summary": 1,
                "uri": 1,
                "source": 1,
                "relevance_score": 1,
                "published_ts": 1,
                "tags": 1,
            },
        )
        .sort([("published_ts", -1), ("relevance_score", -1)])
        .limit(int(limit))
    )
    return list(cur)


def _ensure_min_articles(
    articles: List[Dict[str, Any]], industry_name: str, desired_min: int, verbose: bool
) -> List[Dict[str, Any]]:
    """
    Ensure we have enough articles to feed the LLM.
    Strategy:
      1) If count >= desired_min → return as-is
      2) Else: relax relevance threshold and fetch more industry matches (best-effort)
      3) Else: top-up with recent generic articles
    """
    if len(articles) >= desired_min:
        return articles

    # Try to relax relevance a bit for this industry
    try:
        extra_needed = desired_min - len(articles)
        relaxed = get_industry_articles(
            industry_name=industry_name, limit=extra_needed * 2, min_relevance=0.2
        )
        # Merge (dedupe by uri/title)
        seen = set()
        merged: List[Dict[str, Any]] = []
        for a in articles + relaxed:
            key = a.get("uri") or a.get("ai_title", "")
            if key and key not in seen:
                seen.add(key)
                merged.append(a)
        if len(merged) >= desired_min:
            log(f" Relaxed filter supplied {len(merged)} total articles", verbose)
            return merged[: max(len(articles), desired_min)]
        articles = merged
    except Exception as _:
        pass

    # Still short? Top-up with recent generic articles
    if len(articles) < desired_min:
        top_up = _fetch_recent_generic_articles(
            limit=(desired_min - len(articles) + 5), min_relevance=0.25
        )
        log(f"🧩 Topping up with {len(top_up)} generic articles", verbose)
        seen = set((a.get("uri") or a.get("ai_title", "")) for a in articles)
        for a in top_up:
            key = a.get("uri") or a.get("ai_title", "")
            if key and key not in seen:
                articles.append(a)
                seen.add(key)

    # Cap to a sane number (LLM context)
    return articles[: max(desired_min, min(len(articles), 30))]


def _priority_weight(val: str) -> float:
    table = {"critical": 1.0, "high": 0.85, "medium": 0.6, "low": 0.35}
    return table.get(str(val).lower(), 0.5)


def _impact_weight(val: str) -> float:
    table = {"high": 0.9, "medium": 0.6, "low": 0.3}
    return table.get(str(val).lower(), 0.5)


def _urgency_weight(val: str) -> float:
    table = {"immediate": 1.0, "this week": 0.85, "this month": 0.6, "low": 0.35}
    return table.get(str(val).lower(), 0.5)


def _dedupe_opportunities(items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Deduplicate by (action/headline/opportunity) + source_article if present.
    """
    seen = set()
    out: List[Dict[str, Any]] = []
    for it in items:
        key = (
            (it.get("action") or it.get("headline") or it.get("opportunity") or "")
            .strip()
            .lower(),
            (it.get("source_article") or "").strip().lower(),
        )
        if key not in seen:
            seen.add(key)
            out.append(it)
    return out


def _re_rank_opportunities(items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Add a composite score and sort:
      score = 0.45*priority + 0.35*impact + 0.20*urgency
    Then cap to a clean list.
    """
    scored = []
    for it in items:
        pri = _priority_weight(it.get("priority", it.get("urgency", "medium")))
        imp = _impact_weight(
            it.get("estimated_impact", it.get("potential_impact", "medium"))
        )
        urg = _urgency_weight(it.get("urgency", "this month"))
        score = 0.45 * pri + 0.35 * imp + 0.20 * urg
        it["_score"] = round(float(score), 4)
        scored.append(it)
    scored.sort(key=lambda x: x.get("_score", 0.0), reverse=True)
    return scored


def _fallback_from_articles(
    company_ctx: dict, industry_name: str, articles: List[Dict[str, Any]]
) -> List[Dict[str, Any]]:
    """
    If the LLM call fails or returns empty, produce simple, deterministic opportunities from article titles.
    """
    out = []
    for a in articles[:6]:
        title = a.get("ai_title") or a.get("source") or "Industry update"
        url = a.get("uri", "")
        out.append(
            {
                "category": "opportunity",
                "action": f"Explore partnership or content collab based on: {title}",
                "priority": "high",
                "description": f"Leverage {title} to position {company_ctx['company']} in {industry_name}. Consider a quick outreach or a response article.",
                "source_article": title,
                "source_url": url,
                "estimated_effort": "low",
                "estimated_impact": "medium",
                "urgency": "This week",
            }
        )
    return out


# ---------------------------
# Public API
# ---------------------------


def run(
    company_name: str,
    industry_name: str,
    limit: int = 20,
    min_relevance: float = 0.4,
    verbose: bool = False,
) -> List[Dict[str, Any]]:
    """
    Programmatic entry point for generating growth/partnership/expansion opportunities.
    Robust to sparse industry matches and LLM hiccups.
    """
    try:
        log(f"Loading company context for {company_name}...", verbose)
        company_ctx = get_company_context(company_name)

        log(f" Fetching {limit} recent '{industry_name}' articles...", verbose)
        articles = get_industry_articles(
            industry_name=industry_name,
            limit=limit,
            min_relevance=min_relevance,
        )
        log(f" Found {len(articles)} industry-matching articles", verbose)

        # Ensure we have enough signal to feed the LLM well
        articles = _ensure_min_articles(
            articles, industry_name, desired_min=8, verbose=verbose
        )
        log(f" Using {len(articles)} articles after top-up", verbose)

        # Generate via LLM
        log(" Generating opportunities...", verbose)
        opps = generate_opportunities(
            company_context=company_ctx,
            industry_name=industry_name,
            industry_articles=articles,
        )

        # Guard against non-list returns
        if not isinstance(opps, list):
            raise ValueError("generate_opportunities returned non-list")

        # Deduplicate and re-rank
        opps = _dedupe_opportunities(opps)
        opps = _re_rank_opportunities(opps)

        # Attach industry context for traceability
        for it in opps:
            it.setdefault("industry", industry_name)

        log(f" Generated {len(opps)} opportunities", verbose)

        # Graceful fallback if empty
        if not opps:
            log(
                " LLM returned empty; building deterministic fallbacks from articles",
                verbose,
            )
            opps = _fallback_from_articles(company_ctx, industry_name, articles)
            opps = _re_rank_opportunities(opps)

        return opps

    except Exception as e:
        # Last-resort graceful degradation: return deterministic fallbacks
        try:
            log(
                f"opportunities.run() error: {e}. Falling back to deterministic suggestions.",
                verbose,
            )
            # try to fetch generic articles to seed fallbacks
            articles = _fetch_recent_generic_articles(limit=10, min_relevance=0.25)
            company_ctx = get_company_context(company_name)
            opps = _fallback_from_articles(company_ctx, industry_name, articles)
            return _re_rank_opportunities(opps)
        except Exception as _:
            # If even fallback fails, surface the original error
            raise RuntimeError(f"opportunities.run() failed: {e}") from e


# ---------------------------
# CLI
# ---------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate growth/partnership/expansion opportunities for a given industry view."
    )
    parser.add_argument(
        "company_name", type=str, help="Company name as stored in company_profiles"
    )
    parser.add_argument(
        "industry_name",
        type=str,
        help="Industry/topic/sector currently being viewed (e.g. 'AI in retail')",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=20,
        help="How many recent industry articles to consider",
    )
    parser.add_argument(
        "--min-relevance",
        type=float,
        default=0.4,
        help="Minimum relevance_score threshold in ai_results",
    )
    parser.add_argument(
        "--verbose", action="store_true", help="Show debug/info logs on stderr"
    )
    args = parser.parse_args()

    try:
        result = run(
            company_name=args.company_name,
            industry_name=args.industry_name,
            limit=args.limit,
            min_relevance=args.min_relevance,
            verbose=args.verbose,
        )
        print(json.dumps(result, indent=2))
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
