# AI/collection_card/main_opportunities.py

from pymongo import MongoClient
import argparse
import json
import os
import sys
from bson import ObjectId
from .fetch_industry_articles import get_industry_articles
from .generate_opportunities import generate_opportunities


# --- Mongo bootstrap (same style you're already using)
MONGO_URI = os.getenv(
    "MONGO_URI",
    "mongodb+srv://ai_worker_user:YUiDJwjMqqBKEI70@cluster0.dqugl74.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
)
client = MongoClient(MONGO_URI)
db = client["pace_database"]


def get_company_context(company_id: str):
    """Retrieve company description & competitors from Mongo by ID"""
    try:
        # Convert string ID to ObjectId
        obj_id = ObjectId(company_id)
    except Exception as e:
        raise ValueError(f"Invalid company ID format: {company_id}")
    
    company = db.company_profiles.find_one({"_id": obj_id})
    if not company:
        raise ValueError(f"No company found for ID {company_id}")
    
    return {
        "name": company["name"],
        "description": company["description"],
        "competitors": company["competitors"]
    }

def get_recent_searches(limit=10):
    """Retrieve most recent analyzed topics from ai_results (optional)"""
    cursor = db.ai_results.find(
        {"status": "done"},
        {"ai_title": 1, "_id": 0}
    ).sort("published_ts", -1).limit(limit)
    return [doc["ai_title"] for doc in cursor]

def build_context(company_id: str, limit=10):
    """Build internal company context"""
    company_info = get_company_context(company_id)
    recent_searches = get_recent_searches(limit)

    context = {
        "company": company_info["name"],
        "description": company_info["description"],
        "competitors": company_info["competitors"],
        "recent_searches": recent_searches
    }
    return context


def log(msg: str, verbose: bool):
    if verbose:
        print(msg, file=sys.stderr)

def run(
    company_name: str,
    industry_name: str,
    limit: int = 20,
    min_relevance: float = 0.4,
    verbose: bool = False,
):
    """
    Programmatic entry point for generating growth/partnership/expansion opportunities.

    Mirrors the CLI behavior in __main__.

    Args:
        company_name: Name of the company (must exist in company_profiles)
        industry_name: Industry/topic/sector (e.g., "AI in retail")
        limit: Max number of recent articles to consider (default 20)
        min_relevance: Minimum relevance_score threshold (default 0.4)
        verbose: Print debug messages if True

    Returns:
        List[dict]: structured opportunity insights generated by the AI layer
    """
    try:
        log(f"🏢 Loading company context for {company_name}...", verbose)
        company_ctx = get_company_context(company_name)

        log(f"📰 Fetching {limit} recent '{industry_name}' articles...", verbose)
        articles = get_industry_articles(
            industry_name=industry_name,
            limit=limit,
            min_relevance=min_relevance,
        )
        log(f"✓ Found {len(articles)} industry-matching articles", verbose)

        log("🤖 Generating opportunities...", verbose)
        opps = generate_opportunities(
            company_context=company_ctx,
            industry_name=industry_name,
            industry_articles=articles,
        )
        log(f"✓ Generated {len(opps)} opportunities", verbose)

        return opps

    except Exception as e:
        raise RuntimeError(f"opportunities.run() failed: {e}") from e


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate growth/partnership/expansion opportunities for a given industry view."
    )
    parser.add_argument(
        "company_id",
        type=str,
        help="Company id as stored in company_profiles"
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=20,
        help="How many recent industry articles to consider"
    )
    parser.add_argument(
        "--min-relevance",
        type=float,
        default=0.4,
        help="Minimum relevance_score threshold in ai_results"
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Show debug/info logs on stderr"
    )

    args = parser.parse_args()

    try:
        company_ctx = get_company_context(args.company_id)

        log(f"📰 Fetching {args.limit} recent '{args.industry_name}' articles...", args.verbose)
        articles = get_industry_articles(
            industry_name=args.industry_name,
            limit=args.limit,
            min_relevance=args.min_relevance,
        )
        log(f"✓ Found {len(articles)} industry-matching articles", args.verbose)

        log("🤖 Generating opportunities...", args.verbose)
        opps = generate_opportunities(
            company_context=company_ctx,
            industry_name=args.industry_name,
            industry_articles=articles,
        )
        log(f"✓ Generated {len(opps)} opportunities", args.verbose)

        # Send clean JSON to stdout (frontend/BE reads this)
        print(json.dumps(opps, indent=2))

    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
